/**
 * The numbers and names actuation turns on. All of them are read by
 * deterministic code, and none is ever handed to a model to reinterpret.
 */

import type { TokenGroup } from "../analysis/tokens"

/** Branch a fix for one finding is opened on. */
export function fixBranchName(findingId: string): string {
  return `drift/fix-${findingId}`
}

/** Branch the rules file lives on, and the only branch Drift commits to twice. */
export const RULES_BRANCH = "drift/rules"

/** Where the rules file lands in a watched repo. */
export const RULES_PATH = "drift.rules.md"

/**
 * Branch the before and after images live on. Never merged and never proposed:
 * a pull request from Drift contains the patch and nothing else, and the images
 * its body embeds sit somewhere the patch does not carry them.
 */
export const EVIDENCE_BRANCH = "drift/evidence"

/** Directory the evidence images are written under, inside the evidence branch. */
export const EVIDENCE_DIRECTORY = ".drift/evidence"

/** The line every pull request Drift opens ends with. */
export const OPENED_BY_DRIFT = "Opened by Drift."

/** The first line of every generated rules file. */
export const RULES_HEADER = "Generated by Drift. Do not edit by hand."

/**
 * Most occurrences one mechanical patch may replace. A literal that appears
 * more often than this is a word the product uses everywhere rather than the
 * one label a finding is about, and replacing all of them is not mechanical.
 */
export const MAX_PATCH_OCCURRENCES = 20

/**
 * How far an off-scale value may sit from the token it is snapped to before a
 * pull request needs a person. Colours are OKLab distance, where 0.02 is a
 * value nobody can tell apart and 0.3 is a different colour; lengths are
 * pixels. Past these the nearest token is a guess, and a guess waits.
 */
export const MAX_AUTONOMOUS_DISTANCE: Record<TokenGroup, number> = {
  color: 0.12,
  fontSize: 2,
  spacing: 2,
  radius: 2,
  // Never autonomous: see PATCHABLE_GROUPS.
  fontWeight: 0,
}

/**
 * Token groups a value substitution can be planned for. A font weight is
 * written in source as a bare number, which cannot be told apart from any other
 * bare number without knowing what the code around it means. That is judgment
 * about code structure, which is permanently out of scope, so weights are
 * reported and never patched.
 */
export const PATCHABLE_GROUPS: readonly TokenGroup[] = ["color", "fontSize", "spacing", "radius"]
